CREATE DATABASE Assignment;

use Assignment;

	
		
CREATE TABLE Products(
		
			 ProductID INT,
             ProductName VARCHAR(255),
             DESCRIPTION VARCHAR(255),
             cost INT
);

INSERT INTO PRODUCTS VALUES (1,"Mobile","Gadgets",10000);
INSERT INTO PRODUCTS VALUES (2,"Air Conditioner","AC",4000);
INSERT INTO PRODUCTS VALUES (3,"Washing Machine","Machine",15000);
INSERT INTO PRODUCTS VALUES (4,"earpods","Gadget",500);
INSERT INTO PRODUCTS VALUES (5,"Macbook","Gadget",100000);

SELECT * from PRODUCTS;

CREATE TABLE CUSTOMER(
	
    CUSTOMERID INT,
    CUSTOMERNAME VARCHAR(255),
    ADDRESS VARCHAR(255),
    CITY VARCHAR(255),
    POSTALCODE INT,
    COUNTRY VARCHAR(255)

);

INSERT INTO CUSTOMER VALUES (1,"Navnath","H1 Pune","Maharashtra",5,413203,"INDIA");
INSERT INTO CUSTOMER VALUES (2,"Raj","H2 Pune , Indore","MADHYA PRADESH",5,413203,"INDIA");
INSERT INTO CUSTOMER VALUES (3,"Varun","H3, KAMALA NAGAR","Telengana",5,413210,"INDIA");
INSERT INTO CUSTOMER VALUES (4,"VARUN","HYDERABAD","TELANGANA",123455,"INDIA");
INSERT INTO CUSTOMER VALUES (5,"Sanket","Pune","Maharashtra",5,411048,"INDIA");

SELECT * FROM CUSTOMER;

CREATE TABLE PURCHASE(

	CUSTOMERID INT,
    PRODUCTID INT 

);

INSERT INTO PURCHASE VALUES (1,1);
INSERT INTO PURCHASE VALUES (2,2);
INSERT INTO PURCHASE VALUES (3,3);
INSERT INTO PURCHASE VALUES (4,5);
INSERT INTO PURCHASE VALUES  (5,4);

SELECT * FROM PURCHASE ;


SELECT DISTINCT(CITY) ,COUNT(CITY) AS COUNT FROM CUSTOMER GROUP BY CITY ;

SELECT * FROM PRODUCTS WHERE COST >=18000;

SELECT CUSTOMERID, CUSTOMERNAME, CITY FROM CUSTOMER WHERE CUSTOMERID IN (SELECT CUSTOMERID FROM PURCHASE);

SELECT * FROM PRODUCTS WHERE PRODUCTID IN  (SELECT P.PRODUCTID FROM PURCHASE P, CUSTOMER C WHERE P.PRODUCTID =C.CUSTOMERID );

SELECT CUSTOMERNAME, COUNTRY FROM CUSTOMER WHERE UPPER(COUNTRY)='INDIA';

SELECT CUSTOMERNAME FROM CUSTOMER ORDER BY CUSTOMERNAME;

SELECT CUSTOMERNAME FROM CUSTOMER ORDER BY CUSTOMERNAME ASC ,COUNTRY DESC;

INSERT INTO CUSTOMER (CUSTOMERID , CUSTOMERNAME, ADDRESS,CITY,POSTALCODE,COUNTRY) VALUES  (6,Navnath,'FN 1','HYDERABAD',411048,'INDIA');

INSERT INTO CUSTOMER VALUES (6,"Raj","F2 Pune","Maharashtra",NULL,"INDIA");
SELECT * FROM CUSTOMER WHERE POSTALCODE IS NULL;



SELECT * FROM CUSTOMER WHERE POSTALCODE IS NOT NULL;

SET SQL_SAFE_UPDATES = 0;
UPDATE PRODUCTS SET PRODUCTNAME='VIVO' WHERE PRODUCTNAME='MOBILE';
SELECT * FROM PRODUCTS;


SET SQL_SAFE_UPDATES=0;
UPDATE PRODUCTS SET DESCRIPTION='MOUSE' WHERE PRODUCTID=5  AND PRODUCTNAME='COMPUTER';
SELECT * FROM PRODUCTS;

DELETE FROM CUSTOMER WHERE CUSTOMERID=3;
SELECT * FROM CUSTOMER;

DELETE FROM CUSTOMER;
SELECT * FROM CUSTOMER;

SELECT PRODUCTID , PRODUCTNAME, COST FROM PRODUCTS WHERE COST IN (SELECT MAX(COST) FROM PRODUCTS);

SELECT PRODUCTID,PRODUCTNAME,COST FROM PRODUCTS ORDER BY COST DESC LIMIT 0,1;



SELECT PRODUCTID, PRODUCTNAME FROM PRODUCTS WHERE COST=(SELECT MIN(COST) FROM PRODUCTS);



SELECT SUM((SELECT COST FROM PRODUCTS P WHERE P.PRODUCTID=TEMP.PRODUCTID)*TEMP.PRODUCTCOUNT)
 FROM (SELECT PRODUCTID,COUNT(PRODUCTID) AS PRODUCTCOUNT FROM PURCHASE GROUP BY PRODUCTID) AS TEMP;



ALTER TABLE CUSTOMER RENAME COLUMN POSTALCODE TO PINCODE;

SELECT * FROM CUSTOMER;


ALTER TABLE CUSTOMER ADD RATING INT AFTER CITY;
SELECT * FROM CUSTOMER;


CREATE TABLE STUDENT (

STUDENTID INT,
STUDENTNAME VARCHAR(255)
);
INSERT INTO STUDENT VALUES (1,"Navnath Kumbhar");
INSERT INTO STUDENT VALUES (2,"Raj Gholap");
TRUNCATE TABLE STUDENT;
DROP TABLE STUDENT;
SET AUTOCOMMIT=0;
DELETE FROM CUSTOMER WHERE CUSTOMERID=3;
ROLLBACK;
COMMIT;
SET AUTOCOMMIT=1;
SELECT * FROM CUSTOMER;


SELECT CUSTOMERID, COUNT(PRODUCTID) AS PRODUCTCOUNT FROM PURCHASE GROUP BY CUSTOMERID;


SELECT C.CUSTOMERID , C.CUSTOMERNAME, P.PRODUCTNAME FROM CUSTOMER C , PRODUCTS P , PURCHASE PP 
WHERE C.CUSTOMERID=PP.CUSTOMERID AND P.PRODUCTID=PP.PRODUCTID;











CREATE TABLE EMPLOYEE(
EMPID INT, 
EMPNAME VARCHAR(255),
EMPADDRESS VARCHAR(255),
EMPCITY VARCHAR(255),
EMPSTATE VARCHAR(255),
EMPCOUNTRY VARCHAR(255),
PRIMARY KEY (EMPID)
);

INSERT INTO EMPLOYEE VALUES (1,"Navnath","M1","Pune","Maharashtra","INDIA");
INSERT INTO EMPLOYEE VALUES (2,"Raj","M2","Solapur",” AP","RUSSIA");
INSERT INTO EMPLOYEE VALUES (3,"Varun","A89","PAXTON","NEW YORK","USA");

 CREATE TABLE DEPARTMENT (
 DEPTID INT , 
 DEPTNAME VARCHAR(255),
 EMPID INT,
 CONSTRAINT REF FOREIGN KEY (EMPID) REFERENCES EMPLOYEE(EMPID) 
 );
 
 INSERT INTO DEPARTMENT VALUES(1011,"CSE",1);
 INSERT INTO DEPARTMENT VALUES(1012,"IT",2);
 
 SELECT E.EMPNAME , D.DEPTNAME FROM EMPLOYEE AS  E INNER JOIN DEPARTMENT D ON E.EMPID=D.EMPID;


